spring.application.name=bus

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bus
spring.datasource.username=postgres
spring.datasource.password=hana1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=THIS_IS_A_VERY_LONG_SECRET_KEY_AT_LEAST_32_BYTES
